{% set version = "0.8.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggseqplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggseqplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggseqplot/ggseqplot_{{ version }}.tar.gz
  sha256: 2c26cd5532b99c66f609d6ed2a1192d48059af29745fde804037fa2ac9382623

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rdpack
    - r-traminer >=2.2_5
    - r-cli
    - r-colorspace
    - r-dplyr >=1.1.0
    - r-forcats >=1.0.0
    - r-ggh4x
    - r-ggplot2 >=3.4.0
    - r-ggrepel
    - r-ggtext
    - r-glue
    - r-haven
    - r-patchwork
    - r-purrr
    - r-rlang
    - r-tidyr
    - r-usethis
  run:
    - r-base
    - r-rdpack
    - r-traminer >=2.2_5
    - r-cli
    - r-colorspace
    - r-dplyr >=1.1.0
    - r-forcats >=1.0.0
    - r-ggh4x
    - r-ggplot2 >=3.4.0
    - r-ggrepel
    - r-ggtext
    - r-glue
    - r-haven
    - r-patchwork
    - r-purrr
    - r-rlang
    - r-tidyr
    - r-usethis

test:
  commands:
    - $R -e "library('ggseqplot')"           # [not win]
    - "\"%R%\" -e \"library('ggseqplot')\""  # [win]

about:
  home: https://github.com/maraab23/ggseqplot
  license: GPL-3.0-or-later
  summary: A set of wrapper functions that mainly re-produces some of the sequence plots rendered with TraMineR::seqplot() and 'TraMineRextras'. Whereas 'TraMineR' uses base R to produce the plots this library draws on 'ggplot2'. The plots are produced on the basis of a sequence object defined with TraMineR::seqdef(). The
    package automates the reshaping and plotting of sequence data. Resulting plots are of class 'ggplot', i.e. components can be added and tweaked using '+' and regular 'ggplot2' functions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
